version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      # Don't upgrade spec dependencies past Jakarta EE 10
      - dependency-name: jakarta.faces:jakarta.faces-api
        versions: "[4.1.0,)"
      - dependency-name: jakarta.annotation:jakarta.annotation-api
        versions: "[3.0.0,)"
      - dependency-name: jakarta.servlet:jakarta.servlet-api
        versions: "[6.1.0,)"
      - dependency-name: jakarta.enterprise:jakarta.enterprise.cdi-api
        versions: "[4.1.0,)"
      - dependency-name: jakarta.el:jakarta.el-api
        versions: "[5.0.0,)"
      # Don't upgrade the tomcat servlet api, as it should match the TomEE version, which most probably does not contain a recent version of this artifact.
      - dependency-name: org.apache.tomcat:tomcat-servlet-api
        versions: "[10.1.0,)"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
