name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
    types: [ checks_requested ]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        # Keep this list as: all supported LTS JDKs, the latest GA JDK, and the latest EA JDK (optional).
        java:
          - 11
          - 17
          - 21
          - 23
        container:
          - wildfly-managed
          # TODO GlassFish 5 is not compatible with JDK 9 and newer
          # - glassfish-managed
           - tomee-managed
        exclude:
           # TomEE 10 requires Java 17.
           - os: ubuntu-latest
             java: 11
             container: tomee-managed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: ./mvnw --batch-mode --no-transfer-progress --activate-profiles ${{ matrix.container }} verify
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.container }}
          path: '**/surefire-reports/*.txt'
